version: '2.4'

services:
  broadcast:
    build: .
    environment:
      LOGGING_LEVEL: 'DEBUG'
  logs_event_loop:
    build: .
    environment:
      LOGGING_LEVEL: 'DEBUG'
  welcome_message_loop:
    build: .
    environment:
      LOGGING_LEVEL: 'DEBUG'
  stats:
    build: .
    environment:
      LOGGING_LEVEL: 'DEBUG'
  backend_1:
    environment:
      DJANGO_DEBUG: 'yes'
      LOGGING_LEVEL: 'DEBUG'
    build: .
  frontend:
    build:
      context: ./rcongui
  redis:
    ports: 
      - ${HLL_REDIS_HOST_PORT:-6379}:6379
  postgres:
    ports:
      - ${HLL_DB_HOST_PORT:-5432}:5432
